name = "catppuccin-mocha"

[colors]
bg0    = "#11111b"
bg1    = "#1e1e2e"
bg3    = "#313244"
bg_sel = "#45475a"
fg0    = "#cdd6f4"
fg3    = "#7f849c"
fg4    = "#6c7086"
red    = "#f38ba8"
green  = "#a6e3a1"
yellow = "#f9e2af"
blue   = "#89b4fa"
aqua   = "#94e2d5"
orange = "#fab387"
purple = "#cba6f7"
