name = "everforest"

[colors]
primary = "#83c092"
secondary = "#e67e80"
bg0 = "#1e2326"
bg1 = "#272e33"
bg2 = "#2e383c"
bg_sel = "#374145"
fg0 = "#d3c6aa"
fg1 = "#859289"
fg2 = "#7a8478"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
aqua = "#83c092"
orange = "#e69875"
purple = "#d699b6"
