name = "gruvbox-material"

[colors]
bg0    = "#1d2021"
bg1    = "#282828"
bg3    = "#3c3836"
bg_sel = "#504945"
fg0    = "#d4be98"
fg3    = "#928374"
fg4    = "#7c6f64"
red    = "#ea6962"
green  = "#a9b665"
yellow = "#d8a657"
blue   = "#7daea3"
aqua   = "#89b482"
orange = "#e78a4e"
purple = "#d3869b"
