name = "gruvbox-baby"

[colors]
primary = "#ef9062"
secondary = "#7ab8b8"
bg0 = "#1d2021"
bg1 = "#242424"
bg2 = "#3d3d3d"
bg_sel = "#4e4e4e"
fg0 = "#ebdbb2"
fg1 = "#928374"
fg2 = "#7c6f64"
red = "#e57a8f"
green = "#a6c379"
yellow = "#efb35b"
blue = "#7ab8b8"
aqua = "#8ec07c"
orange = "#ef9062"
purple = "#d797d8"
