name = "gruvbox"

[colors]
bg0 = "#1d2021"
bg1 = "#282828"
bg3 = "#3c3836"
bg_sel = "#504945"
fg0 = "#ebdbb2"
fg3 = "#a89984"
fg4 = "#7c6f64"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
aqua = "#8ec07c"
orange = "#fe8019"
purple = "#d3869b"
