name = "tokyo-night"

[colors]
bg0 = "#16161e"
bg1 = "#1a1b26"
bg2 = "#24283b"
bg_sel = "#283457"
fg0 = "#c0caf5"
fg1 = "#565f89"
fg2 = "#3b4261"
primary = "#7aa2f7"
secondary = "#9d7cd8"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
aqua = "#2ac3de"
orange = "#ff9e64"
purple = "#bb9af7"
